# Generated by Django 5.0.4 on 2025-02-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='coot_time',
            new_name='cook_time',
        ),
    ]
