# Generated by Django 5.0.4 on 2025-02-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desc',
            new_name='description',
        ),
    ]
