# Generated by Django 5.0.4 on 2025-02-17 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 2, 17), null=True, verbose_name='Start Date'),
        ),
    ]
